### ISSUE TITLE
prefixing drive path twice while generating swagger.json file

### ISSUE THREAD

**Issue by MadhavGutte** [llucasspot/adonisjs-6-swagger#1]
Error: ENOENT: no such file or directory, open 'D:\D:\Projects
**D:** is prefixed twice hence throwing no such file or directory error

**Comment by llucasspot** [comment]
I have no pb on mac os
do you have more details of the issue ? 

you shoudl have the config file generated like : 

```
import { SwaggerConfig } from 'adonisjs-6-swagger'

export default {
  uiEnabled: true, //disable or enable swaggerUi route
  uiUrl: 'docs', // url path to swaggerUI
  specEnabled: true, //disable or enable swagger.json route
  specUrl: '/swagger.json',

  middleware: [], // middlewares array, for protect your swagger docs and spec endpoints

  options: {
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'Application with swagger docs',
        version: '1.0.0',
        description: 'My application with swagger docs',
      },
    },

    apis: ['app/**/*.ts', 'docs/swagger/**/*.yml', 'start/routes.ts'],
    basePath: '/',
  },
  mode: process.env.NODE_ENV === 'production' ? 'PRODUCTION' : 'RUNTIME',
  specFilePath: 'docs/swagger.json',
} as SwaggerConfig
```

**Comment by llucasspot** [comment]
the the swagger json file is not saving  in the docs folder ?

**Comment by MadhavGutte** [comment]
yes I do have config file generated similar to what you shared above.  But it doesn't create json file, and given the no such file error with path with twice D: . I also tries manually creating docs folder in my project root files but didn't work. I am using windows OS.

**Comment by MadhavGutte** [comment]
Please ignore the issue, it has nothing to do with your library, adonisjs 6 gives incorrect root path by prefixing the absolute path with / and hence program automatically prefixes the drive name again.

**Comment by llucasspot** [comment]
ow does the Adonis issue is fixed ?

**Comment by MadhavGutte** [comment]
Not yet, I will try to raise this with adonisjs support after detailed investigation.

**Comment by llucasspot** [comment]
new patch was release, comfirm me the fix please
