### ISSUE TITLE
swagger.json not generated

### ISSUE THREAD

**Issue by aaumond** [llucasspot/adonisjs-6-swagger#4]
Hi,

When I launch my adonis server using the `node ace serve -watch` command, everything goes fine and the API works correctly.

If I run the command to generate the swagger config, it succeeds: 
`node ace configure adonisjs-6-swagger`

```
(node:87254) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
DONE: create config/swagger.ts
DONE: update adonisrc.ts file
```

The configuration file is visible.

<img width="836" alt="Capture d’écran 2024-06-06 à 16 56 31" src="https://github.com/llucasspot/adonisjs-6-swagger/assets/79145906/d1baf9da-ed9c-4dcc-99e3-70e8008655cf">

However, the server tries to rebuild the application and fails because the /docs/swagger.json file is not generated. How can I generate it (I haven't found any more information in the library documentation)?

```
update adonisrc.ts
(node:87266) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

   Error: ENOENT: no such file or directory, open '/Users/anthony.aumond/Documents/Projects/commu-backend/back-quiz/docs/swagger.json'
 

   ⁃ ProvidersManager.boot
     node_modules/@adonisjs/application/src/managers/providers.ts:175
   ⁃ Application.boot
     node_modules/@adonisjs/application/src/application.ts:493

[ info ] Underlying HTTP server died. Still watching for changes

```

Thanks in advance

**Comment by llucasspot** [comment]
Hello, i have an issues with windows users.
the probleme is with adonis `this.app.appRoot.pathname` variable.
Some users was having two C:/C: in their path by exemple, so i have done a fix to remove one (see : https://github.com/llucasspot/adonisjs-6-swagger/commit/928e0ef95d6acc1d6e95b508db3c6312aa011d0a)

i see that you didnt have C:/ or D:/ in your path. 

unfortunatly i dont have window os to test my lib.
Can you build the lib and fix the issues on your own ?

**Comment by aaumond** [comment]
Thanks @llucasspot for your answer.
I saw this issue but I'm on Mac (Sonoma)...

**Comment by llucasspot** [comment]
Does a folder docs exists on your root path projet ?

**Comment by aaumond** [comment]
@llucasspot  I hadn't created the docs folder, believing that it was created automatically by the package.

Now, a `swagger.json file` is generated in the `/docs` folder, it contains the API documentation for my controllers but the UI doesn't seem to use this `swagger.json` file as it has an empty doc.

API docs :
<img width="1522" alt="Capture d’écran 2024-06-10 à 09 06 32" src="https://github.com/llucasspot/adonisjs-6-swagger/assets/79145906/2a26031f-6545-4bec-aaf8-ee6f369357c6">

JSON : 
<img width="663" alt="Capture d’écran 2024-06-10 à 09 15 29" src="https://github.com/llucasspot/adonisjs-6-swagger/assets/79145906/249dc585-5f54-4450-b5ad-c989eef74fcf">

**Comment by llucasspot** [comment]
No worries, you are right the librairie should do it 

I see that your path and the post key are not well indented 
Can you show me the comment swagger code in your code ?

I think that is because of the indentation that you put on the comment.

**Comment by aaumond** [comment]
Here my swagger code :
<img width="543" alt="Capture d’écran 2024-06-10 à 09 10 51" src="https://github.com/llucasspot/adonisjs-6-swagger/assets/79145906/bba9cb88-b294-4330-ade3-b772cb82c7a0">

We can see the `swagger.json` generated is good..

**Comment by llucasspot** [comment]
Can you add an indentation between the path "/auth/register:" and "post" ?

**Comment by llucasspot** [comment]
![image](https://github.com/llucasspot/adonisjs-6-swagger/assets/153968027/22072f5d-b589-41f3-98a7-306bf2bf7633)

**Comment by aaumond** [comment]
@llucasspot thanks, it works!

**Comment by llucasspot** [comment]
@aaumond welcome
I'm glad to see the library being used even with these issues
